.TH "regex.cpp" 3 "Вс 14 Апр 2019" "Battleship-Royale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
regex.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <boost/regex\&.hpp>\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBtest\fP ()"
.br
.ti -1c
.RI "void \fBtest1\fP ()"
.br
.ti -1c
.RI "void \fBtest2\fP ()"
.br
.ti -1c
.RI "void \fBtest3\fP ()"
.br
.ti -1c
.RI "void \fBtest4\fP ()"
.br
.ti -1c
.RI "void \fBtest5\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Функции"
.PP 
.SS "int main ()"

.PP
См\&. определение в файле asio/regex/regex\&.cpp строка 15
.SS "void test ()"

.PP
См\&. определение в файле asio/regex/regex\&.cpp строка 93
.SS "void test1 ()"

.PP
См\&. определение в файле asio/regex/regex\&.cpp строка 130
.SS "void test2 ()"

.PP
См\&. определение в файле asio/regex/regex\&.cpp строка 55
.SS "void test3 ()"

.PP
См\&. определение в файле asio/regex/regex\&.cpp строка 46
.SS "void test4 ()"

.PP
См\&. определение в файле asio/regex/regex\&.cpp строка 37
.SS "void test5 ()"

.PP
См\&. определение в файле asio/regex/regex\&.cpp строка 21
.SH "Автор"
.PP 
Автоматически создано Doxygen для Battleship-Royale из исходного текста\&.
