.TH "BattleshipRoyale.h" 3 "Вс 14 Апр 2019" "Battleship-Royale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BattleshipRoyale.h \- Заголовочный файл с пространством имён, которое хранит в себе константы\&.  

.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "struct \fBCoockie\fP"
.br
.ti -1c
.RI "struct \fBUID\fP"
.br
.ti -1c
.RI "struct \fBPos\fP"
.br
.ti -1c
.RI "struct \fBSize\fP"
.br
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI " \fBBR\fP"
.br
.RI "Пространство имён с константами "
.in -1c
.SS "Переменные"

.in +1c
.ti -1c
.RI "const int \fBBR::SERVER_VERSION_MAJOR\fP = 0"
.br
.RI "Сервер\&. Major версия "
.ti -1c
.RI "const int \fBBR::SERVER_VERSION_MINOR\fP = 2"
.br
.RI "Сервер\&. Minor версия "
.ti -1c
.RI "const int \fBBR::SERVER_VERSION_PATCH\fP = 5"
.br
.RI "Сервер\&. Path версия "
.ti -1c
.RI "const int \fBBR::CLIENT_VERSION_MAJOR\fP = 0"
.br
.RI "Клиент\&. Major версия "
.ti -1c
.RI "const int \fBBR::CLIENT_VERSION_MINOR\fP = 1"
.br
.RI "Клиент\&. Minor версия "
.ti -1c
.RI "const int \fBBR::CLIENT_VERSION_PATCH\fP = 3"
.br
.RI "Клиент\&. Path версия "
.ti -1c
.RI "const int \fBBR::SERVER_VERSION\fP = (SERVER_VERSION_MAJOR * 10000 + SERVER_VERSION_MINOR * 100 + SERVER_VERSION_PATCH)"
.br
.RI "Версия Сервера "
.ti -1c
.RI "const int \fBBR::CLIENT_VERSION\fP = (CLIENT_VERSION_MAJOR * 10000 + CLIENT_VERSION_MINOR * 100 + CLIENT_VERSION_PATCH)"
.br
.RI "Версия клиента "
.ti -1c
.RI "const char \fBBR::DB_NAME\fP [] = 'test\&.db'"
.br
.RI "Название базы данных "
.ti -1c
.RI "const char \fBBR::SERVER_IP\fP [] = '127\&.0\&.0\&.1'"
.br
.RI "Стандартный адрес сервера "
.ti -1c
.RI "const int \fBBR::SERVER_PORT\fP = 1234"
.br
.RI "Стандартный порт сервера "
.ti -1c
.RI "const char \fBBR::REG_USER\fP [] = '^user:\\\\[([^\\\\[\\\\]]+)\\\\]$'"
.br
.ti -1c
.RI "const char \fBBR::REG_USER_PASS\fP [] = '^user:\\\\[([^\\\\[\\\\]]+)\\\\] pass:\\\\[([^\\\\[\\\\]]+)\\\\]$'"
.br
.ti -1c
.RI "const char \fBBR::REG_UID\fP [] = '^UID:\\\\[([^\\\\[\\\\]]+)\\\\] data:\\\\[([^\\\\[\\\\]]+)\\\\]$'"
.br
.in -1c
.SH "Подробное описание"
.PP 
Заголовочный файл с пространством имён, которое хранит в себе константы\&. 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP
\fBДата:\fP
.RS 4
13 Apr 2019 
.RE
.PP

.PP
См\&. определение в файле \fBBattleshipRoyale\&.h\fP
.SH "Автор"
.PP 
Автоматически создано Doxygen для Battleship-Royale из исходного текста\&.
