.TH "battleship-royale" 3 "Сб 13 Апр 2019" "Battleship-Royale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
battleship-royale \- Общие файлы  

.SH SYNOPSIS
.br
.PP
.SS "Группы"

.in +1c
.ti -1c
.RI "\fBBattleShiproyale\&.h\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Общие файлы 


.SH "Автор"
.PP 
Автоматически создано Doxygen для Battleship-Royale из исходного текста\&.
