.TH "battleshiproyalecpp" 3 "Сб 13 Апр 2019" "Battleship-Royale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
battleshiproyalecpp
.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.RI "Точка входа в программу "
.in -1c
.SH "Подробное описание"
.PP 

.SH "Функции"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Точка входа в программу 
.PP
\fBАргументы:\fP
.RS 4
\fIargc\fP количество аргументов для парсера 
.br
\fIargv[]\fP аргументы для парсера 
.RE
.PP
\fBВозвращает:\fP
.RS 4
0 - успешное выполнение программы, 1 - выполнение программы с ошибкой\&. 
.RE
.PP

.PP
См\&. определение в файле server/src/BattleshipRoyale\&.cpp строка 38
.SH "Автор"
.PP 
Автоматически создано Doxygen для Battleship-Royale из исходного текста\&.
