.TH "battleshiproyale" 3 "Сб 13 Апр 2019" "Battleship-Royale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
battleshiproyale
.SH SYNOPSIS
.br
.PP
.SS "Пространства имен"

.in +1c
.ti -1c
.RI " \fBBR\fP"
.br
.RI "Пространство имён с константами "
.in -1c
.SS "Классы"

.in +1c
.ti -1c
.RI "struct \fBCoockie\fP"
.br
.ti -1c
.RI "struct \fBUID\fP"
.br
.ti -1c
.RI "struct \fBPos\fP"
.br
.ti -1c
.RI "struct \fBSize\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 

.SH "Автор"
.PP 
Автоматически создано Doxygen для Battleship-Royale из исходного текста\&.
