.TH "Содержание директории src" 3 "Сб 13 Апр 2019" "Battleship-Royale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории src
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBserver/src/BattleshipRoyale\&.cpp\fP"
.br
.RI "Сервер "
.ti -1c
.RI "файл \fBserver/src/con_handler\&.cpp\fP"
.br
.ti -1c
.RI "файл \fBserver/src/con_handler\&.h\fP"
.br
.ti -1c
.RI "файл \fBDB\&.cpp\fP"
.br
.ti -1c
.RI "файл \fBDB\&.h\fP"
.br
.ti -1c
.RI "файл \fBserver/src/Message\&.h\fP"
.br
.ti -1c
.RI "файл \fBrand_sse\&.cpp\fP"
.br
.RI "Генерация рандомных чисел через SSE\&. "
.ti -1c
.RI "файл \fBrand_sse\&.h\fP"
.br
.RI "Генерация рандомных чисел через SSE\&. "
.ti -1c
.RI "файл \fBserver/src/regex\&.cpp\fP"
.br
.RI "Работа с регулярными выражениями "
.ti -1c
.RI "файл \fBRegex\&.h\fP"
.br
.RI "Работа с регулярными выражениями "
.ti -1c
.RI "файл \fBserver/src/Server\&.cpp\fP"
.br
.ti -1c
.RI "файл \fBserver/src/Server\&.h\fP"
.br
.in -1c
