.TH "Содержание директории BattleshipRoyale" 3 "Вс 14 Апр 2019" "Battleship-Royale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории BattleshipRoyale
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBBattleshipRoyale\&.h\fP"
.br
.RI "Заголовочный файл с пространством имён, которое хранит в себе константы\&. "
.in -1c
