.TH "con_handler" 3 "Вс 14 Апр 2019" "Battleship-Royale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
con_handler
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <con_handler\&.h>\fP
.PP
Базовые классы:enable_shared_from_this< con_handler > и enable_shared_from_this< con_handler >\&.
.SS "Открытые типы"

.in +1c
.ti -1c
.RI "typedef boost::shared_ptr< \fBcon_handler\fP > \fBpointer\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< \fBcon_handler\fP > \fBpointer\fP"
.br
.in -1c
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBcon_handler\fP (boost::asio::io_service &io_service)"
.br
.ti -1c
.RI "boost::asio::ip::tcp::socket & \fBsocket\fP ()"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBhandle_read\fP (const boost::system::error_code &err, size_t bytes_transferred)"
.br
.ti -1c
.RI "void \fBhandle_write\fP (const boost::system::error_code &err, size_t bytes_transferred)"
.br
.ti -1c
.RI "\fB~con_handler\fP ()"
.br
.ti -1c
.RI "\fBcon_handler\fP (boost::asio::io_service &io_service)"
.br
.ti -1c
.RI "boost::asio::ip::tcp::socket & \fBsocket\fP ()"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBhandle_read\fP (const boost::system::error_code &err, size_t bytes_transferred)"
.br
.ti -1c
.RI "void \fBhandle_write\fP (const boost::system::error_code &err, size_t bytes_transferred)"
.br
.ti -1c
.RI "\fB~con_handler\fP ()"
.br
.in -1c
.SS "Открытые статические члены"

.in +1c
.ti -1c
.RI "static \fBpointer\fP \fBcreate\fP (boost::asio::io_service &io_service)"
.br
.ti -1c
.RI "static \fBpointer\fP \fBcreate\fP (boost::asio::io_service &io_service)"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле asio/server/con_handler\&.h строка 7
.SH "Определения типов"
.PP 
.SS "typedef boost::shared_ptr<\fBcon_handler\fP> \fBcon_handler::pointer\fP"

.PP
См\&. определение в файле asio/server/con_handler\&.h строка 16
.SS "typedef boost::shared_ptr<\fBcon_handler\fP> \fBcon_handler::pointer\fP"

.PP
См\&. определение в файле server/src/con_handler\&.h строка 16
.SH "Конструктор(ы)"
.PP 
.SS "con_handler::con_handler (boost::asio::io_service & io_service)\fC [inline]\fP"

.PP
См\&. определение в файле asio/server/con_handler\&.h строка 17
.SS "con_handler::~con_handler ()"

.PP
См\&. определение в файле asio/server/con_handler\&.cpp строка 45
.SS "con_handler::con_handler (boost::asio::io_service & io_service)\fC [inline]\fP"

.PP
См\&. определение в файле server/src/con_handler\&.h строка 17
.SS "con_handler::~con_handler ()"

.SH "Методы"
.PP 
.SS "static \fBpointer\fP con_handler::create (boost::asio::io_service & io_service)\fC [inline]\fP, \fC [static]\fP"

.PP
См\&. определение в файле asio/server/con_handler\&.h строка 21
.SS "static \fBpointer\fP con_handler::create (boost::asio::io_service & io_service)\fC [inline]\fP, \fC [static]\fP"

.PP
См\&. определение в файле server/src/con_handler\&.h строка 21
.SS "void con_handler::handle_read (const boost::system::error_code & err, size_t bytes_transferred)"

.PP
См\&. определение в файле asio/server/con_handler\&.cpp строка 19
.SS "void con_handler::handle_read (const boost::system::error_code & err, size_t bytes_transferred)"

.SS "void con_handler::handle_write (const boost::system::error_code & err, size_t bytes_transferred)"

.PP
См\&. определение в файле asio/server/con_handler\&.cpp строка 32
.SS "void con_handler::handle_write (const boost::system::error_code & err, size_t bytes_transferred)"

.SS "boost::asio::ip::tcp::socket& con_handler::socket ()"

.SS "boost::asio::ip::tcp::socket & con_handler::socket ()"

.PP
См\&. определение в файле asio/server/con_handler\&.cpp строка 8
.SS "void con_handler::start ()"

.PP
См\&. определение в файле asio/server/con_handler\&.cpp строка 13
.SS "void con_handler::start ()"


.SH "Автор"
.PP 
Автоматически создано Doxygen для Battleship-Royale из исходного текста\&.
