.TH "con_handler_cpp" 3 "Вс 14 Апр 2019" "Battleship-Royale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
con_handler_cpp
.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "boost::asio::ip::tcp::socket & \fBcon_handler::socket\fP ()"
.br
.RI "Сокет "
.ti -1c
.RI "void \fBcon_handler::start\fP ()"
.br
.RI "Запуск handler\&. "
.ti -1c
.RI "void \fBcon_handler::handle_read\fP (const boost::system::error_code &err, size_t bytes_transferred)"
.br
.RI "Чтение сообщения от клиента "
.ti -1c
.RI "void \fBcon_handler::handle_write\fP (const boost::system::error_code &err, size_t bytes_transferred)"
.br
.RI "Отправка сообщения клиенту "
.ti -1c
.RI "\fBcon_handler::~con_handler\fP ()"
.br
.RI "Деструктор класса "
.in -1c
.SH "Подробное описание"
.PP 

.SH "Функции"
.PP 
.SS "void con_handler::handle_read (const boost::system::error_code & err, size_t bytes_transferred)"

.PP
Чтение сообщения от клиента 
.PP
\fBАргументы:\fP
.RS 4
\fIerr\fP ошибка 
.br
\fIbytes_transferred\fP 
.RE
.PP

.PP
См\&. определение в файле asio/server/con_handler\&.cpp строка 19
.SS "void con_handler::handle_write (const boost::system::error_code & err, size_t bytes_transferred)"

.PP
Отправка сообщения клиенту 
.PP
\fBАргументы:\fP
.RS 4
\fIerr\fP ошибка 
.br
\fIbytes_transferred\fP 
.RE
.PP

.PP
См\&. определение в файле asio/server/con_handler\&.cpp строка 32
.SS "boost::asio::ip::tcp::socket & con_handler::socket ()"

.PP
Сокет 
.PP
\fBВозвращает:\fP
.RS 4
Сокет 
.RE
.PP

.PP
См\&. определение в файле asio/server/con_handler\&.cpp строка 8
.SS "void con_handler::start ()"

.PP
Запуск handler\&. 
.PP
См\&. определение в файле asio/server/con_handler\&.cpp строка 13
.SS "con_handler::~con_handler ()"

.PP
Деструктор класса 
.PP
См\&. определение в файле asio/server/con_handler\&.cpp строка 45
.SH "Автор"
.PP 
Автоматически создано Doxygen для Battleship-Royale из исходного текста\&.
