.TH "Coockie" 3 "Вс 14 Апр 2019" "Battleship-Royale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Coockie
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BattleshipRoyale\&.h>\fP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "unsigned int \fBu_i_random\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле BattleshipRoyale\&.h строка 117
.SH "Данные класса"
.PP 
.SS "int Coockie::id"

.PP
См\&. определение в файле BattleshipRoyale\&.h строка 120
.SS "unsigned int Coockie::u_i_random"

.PP
См\&. определение в файле BattleshipRoyale\&.h строка 123

.SH "Автор"
.PP 
Автоматически создано Doxygen для Battleship-Royale из исходного текста\&.
