.TH "DB" 3 "Вс 14 Апр 2019" "Battleship-Royale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DB \- Подключение к базе данных  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DB\&.h>\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBDB\fP ()"
.br
.RI "Конструктор класса "
.ti -1c
.RI "void \fBdb_add_player\fP (\fBlogin\fP *l)"
.br
.RI "Создать пользователя l\&. "
.ti -1c
.RI "bool \fBdb_check_player\fP (std::string *s_name)"
.br
.RI "Проверка существования пользователя "
.ti -1c
.RI "void \fBdb_get_player\fP (std::string *name, \fBdb_player\fP *pl)"
.br
.RI "Получить карточку пользователя \fBdb_player\fP по ссылке "
.ti -1c
.RI "int \fBdb_get_id\fP (std::string *s_name)"
.br
.RI "Получение id пользователя по имени\&. id уникальный "
.ti -1c
.RI "bool \fBdb_check_pass\fP (\fBlogin\fP *l)"
.br
.RI "Проверка пароля "
.ti -1c
.RI "\fBUID\fP \fBuid_get_np\fP (\fBlogin\fP *l)"
.br
.RI "Получение \fBUID\fP пользователя "
.ti -1c
.RI "\fBUID\fP \fBuid_get_np\fP (\fBlogin\fP *l, int *id)"
.br
.RI "Получение \fBUID\fP пользователя "
.ti -1c
.RI "std::string \fBdb_get_reg_date\fP (std::string *s_name)"
.br
.RI "Получение даты регистрации по имени "
.ti -1c
.RI "std::string \fBdb_get_password\fP (std::string *s_name)"
.br
.RI "Получение пароля по имени "
.ti -1c
.RI "int \fBdb_get_score\fP (std::string *s_name)"
.br
.RI "Получение результата по имени "
.ti -1c
.RI "int \fBdb_get_money\fP (std::string *s_name)"
.br
.RI "Получение счёта по имени "
.ti -1c
.RI "int \fBdb_get_level\fP (std::string *s_name)"
.br
.RI "Получение уровня доступа по имени "
.ti -1c
.RI "\fB~DB\fP ()"
.br
.RI "Деструктор класса "
.in -1c
.SH "Подробное описание"
.PP 
Подключение к базе данных 
.PP
См\&. определение в файле DB\&.h строка 58
.SH "Методы"
.PP 
.SS "bool DB::db_check_pass (\fBlogin\fP * l)"

.PP
Проверка пароля 
.PP
\fBАргументы:\fP
.RS 4
\fIl\fP пользователь 
.RE
.PP
\fBВозвращает:\fP
.RS 4
true - пароль правильный, false - пароль не правильный\&. 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для Battleship-Royale из исходного текста\&.
