.TH "db_player" 3 "Сб 13 Апр 2019" "Battleship-Royale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
db_player
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DB\&.h>\fP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "std::string \fBpassword\fP"
.br
.ti -1c
.RI "std::string \fBreg_date\fP"
.br
.ti -1c
.RI "int \fBscore\fP"
.br
.ti -1c
.RI "int \fBmoney\fP"
.br
.ti -1c
.RI "int \fBlevel\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле DB\&.h строка 9
.SH "Данные класса"
.PP 
.SS "int db_player::id"

.PP
См\&. определение в файле DB\&.h строка 12
.SS "int db_player::level"

.PP
См\&. определение в файле DB\&.h строка 35
.SS "int db_player::money"

.PP
См\&. определение в файле DB\&.h строка 27
.SS "std::string db_player::name"

.PP
См\&. определение в файле DB\&.h строка 15
.SS "std::string db_player::password"

.PP
См\&. определение в файле DB\&.h строка 18
.SS "std::string db_player::reg_date"

.PP
См\&. определение в файле DB\&.h строка 21
.SS "int db_player::score"

.PP
См\&. определение в файле DB\&.h строка 24

.SH "Автор"
.PP 
Автоматически создано Doxygen для Battleship-Royale из исходного текста\&.
