.TH "Message" 3 "Сб 13 Апр 2019" "Battleship-Royale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Message
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message\&.h>\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBMessage\fP (\fBMessageObject\fP obj)"
.br
.ti -1c
.RI "std::string \fBToSend\fP ()"
.br
.ti -1c
.RI "\fBMessageObject\fP \fBGetObject\fP (const std::string &msg)"
.br
.ti -1c
.RI "\fBMessage\fP (\fBMessageObject\fP obj)"
.br
.ti -1c
.RI "std::string \fBToSend\fP ()"
.br
.ti -1c
.RI "\fBMessageObject\fP \fBGetObject\fP (const std::string &msg)"
.br
.in -1c
.SS "Защищенные данные"

.in +1c
.ti -1c
.RI "virtual std::string \fBcode\fP = '00|'"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле client/src/Message\&.h строка 5
.SH "Конструктор(ы)"
.PP 
.SS "Message::Message (\fBMessageObject\fP obj)\fC [inline]\fP"

.PP
См\&. определение в файле client/src/Message\&.h строка 14
.SS "Message::Message (\fBMessageObject\fP obj)\fC [inline]\fP"

.PP
См\&. определение в файле server/src/Message\&.h строка 14
.SH "Методы"
.PP 
.SS "\fBMessageObject\fP Message::GetObject (const std::string & msg)\fC [inline]\fP"

.PP
См\&. определение в файле client/src/Message\&.h строка 21
.SS "\fBMessageObject\fP Message::GetObject (const std::string & msg)\fC [inline]\fP"

.PP
См\&. определение в файле server/src/Message\&.h строка 21
.SS "std::string Message::ToSend ()\fC [inline]\fP"

.PP
См\&. определение в файле server/src/Message\&.h строка 16
.SS "std::string Message::ToSend ()\fC [inline]\fP"

.PP
См\&. определение в файле client/src/Message\&.h строка 16
.SH "Данные класса"
.PP 
.SS "std::string Message::code = '00|'\fC [protected]\fP"

.PP
См\&. определение в файле client/src/Message\&.h строка 11

.SH "Автор"
.PP 
Автоматически создано Doxygen для Battleship-Royale из исходного текста\&.
