.TH "MessageObject" 3 "Сб 13 Апр 2019" "Battleship-Royale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MessageObject
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message\&.h>\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "virtual std::string \fBToMessage\fP ()"
.br
.ti -1c
.RI "virtual std::string \fBToMessage\fP ()"
.br
.in -1c
.SS "Открытые статические члены"

.in +1c
.ti -1c
.RI "static virtual \fBMessageObject\fP \fBFromMessage\fP (const std::string &msg)"
.br
.ti -1c
.RI "static virtual \fBMessageObject\fP \fBFromMessage\fP (const std::string &msg)"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле client/src/Message\&.h строка 27
.SH "Методы"
.PP 
.SS "static virtual \fBMessageObject\fP MessageObject::FromMessage (const std::string & msg)\fC [inline]\fP, \fC [static]\fP, \fC [virtual]\fP"

.PP
См\&. определение в файле client/src/Message\&.h строка 35
.SS "static virtual \fBMessageObject\fP MessageObject::FromMessage (const std::string & msg)\fC [inline]\fP, \fC [static]\fP, \fC [virtual]\fP"

.PP
См\&. определение в файле server/src/Message\&.h строка 35
.SS "virtual std::string MessageObject::ToMessage ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
См\&. определение в файле server/src/Message\&.h строка 30
.SS "virtual std::string MessageObject::ToMessage ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
См\&. определение в файле client/src/Message\&.h строка 30

.SH "Автор"
.PP 
Автоматически создано Doxygen для Battleship-Royale из исходного текста\&.
