.TH "rand_sse.h" 3 "Сб 13 Апр 2019" "Battleship-Royale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rand_sse.h
.SH SYNOPSIS
.br
.PP
.SS "Макросы"

.in +1c
.ti -1c
.RI "#define \fBCOMPATABILITY\fP"
.br
.in -1c
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBsrand_sse\fP (unsigned int seed)"
.br
.ti -1c
.RI "void \fBrand_sse\fP (unsigned int *)"
.br
.in -1c
.SH "Макросы"
.PP 
.SS "#define COMPATABILITY"

.PP
См\&. определение в файле rand_sse\&.h строка 30
.SH "Функции"
.PP 
.SS "void rand_sse (unsigned int *)"

.PP
См\&. определение в файле rand_sse\&.cpp строка 19
.SS "void srand_sse (unsigned int seed)"

.PP
См\&. определение в файле rand_sse\&.cpp строка 14
.SH "Автор"
.PP 
Автоматически создано Doxygen для Battleship-Royale из исходного текста\&.
