.TH "Regex.cpp" 3 "Вс 14 Апр 2019" "Battleship-Royale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Regex.cpp \- Работа с регулярными выражениями  

.SH SYNOPSIS
.br
.PP
\fC#include 'Regex\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <boost/regex\&.hpp>\fP
.br
\fC#include 'BattleshipRoyale\&.h'\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "bool \fBcheck_pattern\fP (std::string *msg, std::string *pattern)"
.br
.RI "Проверка соответствия строки паттерну "
.ti -1c
.RI "void \fBgetData\fP (std::string *msg, std::string *pattern, std::string *ret_one)"
.br
.RI "Получение информации из строки "
.ti -1c
.RI "void \fBgetData\fP (std::string *msg, std::string *pattern, std::string *ret_one, std::string *ret_two)"
.br
.RI "Получение информации из строки "
.in -1c
.SH "Подробное описание"
.PP 
Работа с регулярными выражениями 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP
\fBДата:\fP
.RS 4
13 Apr 2019 
.RE
.PP

.PP
См\&. определение в файле \fBserver/src/regex\&.cpp\fP
.SH "Автор"
.PP 
Автоматически создано Doxygen для Battleship-Royale из исходного текста\&.
