.TH "Message.h" 3 "Сб 13 Апр 2019" "Battleship-Royale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Message.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBMessage\fP"
.br
.ti -1c
.RI "class \fBMessageObject\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Battleship-Royale из исходного текста\&.
