.TH "UID" 3 "Сб 13 Апр 2019" "Battleship-Royale" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UID
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BattleshipRoyale\&.h>\fP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "std::string \fBs_name\fP"
.br
.ti -1c
.RI "\fBCoockie\fP \fBco_uid\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле BattleshipRoyale\&.h строка 127
.SH "Данные класса"
.PP 
.SS "\fBCoockie\fP UID::co_uid"

.PP
См\&. определение в файле BattleshipRoyale\&.h строка 133
.SS "std::string UID::s_name"

.PP
См\&. определение в файле BattleshipRoyale\&.h строка 130

.SH "Автор"
.PP 
Автоматически создано Doxygen для Battleship-Royale из исходного текста\&.
