var files_dup =
[
    [ "async.cpp", "async_8cpp.html", "async_8cpp" ],
    [ "client/src/BattleshipRoyale.cpp", "client_2src_2_battleship_royale_8cpp.html", "client_2src_2_battleship_royale_8cpp" ],
    [ "server/src/BattleshipRoyale.cpp", "server_2src_2_battleship_royale_8cpp.html", "server_2src_2_battleship_royale_8cpp" ],
    [ "BattleshipRoyale.h", "_battleship_royale_8h.html", "_battleship_royale_8h" ],
    [ "client.cpp", "client_8cpp.html", "client_8cpp" ],
    [ "Client.h", "_client_8h.html", "_client_8h" ],
    [ "server/src/con_handler.cpp", "server_2src_2con__handler_8cpp.html", null ],
    [ "testing/server/con_handler.cpp", "testing_2server_2con__handler_8cpp.html", null ],
    [ "server/src/con_handler.h", "server_2src_2con__handler_8h.html", null ],
    [ "testing/server/con_handler.h", "testing_2server_2con__handler_8h.html", null ],
    [ "DB.cpp", "_d_b_8cpp.html", null ],
    [ "DB.h", "_d_b_8h.html", null ],
    [ "mem.cpp", "mem_8cpp.html", "mem_8cpp" ],
    [ "MemDBmap.cpp", "_mem_d_bmap_8cpp.html", null ],
    [ "MemDBmap.h", "_mem_d_bmap_8h.html", null ],
    [ "MemDBuid.cpp", "_mem_d_buid_8cpp.html", null ],
    [ "MemDBuid.h", "_mem_d_buid_8h.html", null ],
    [ "client/src/Message.h", "client_2src_2_message_8h.html", [
      [ "Message", "class_message.html", "class_message" ],
      [ "MessageObject", "class_message_object.html", "class_message_object" ]
    ] ],
    [ "server/src/Message.h", "server_2src_2_message_8h.html", [
      [ "Message", "class_message.html", "class_message" ],
      [ "MessageObject", "class_message_object.html", "class_message_object" ]
    ] ],
    [ "examples/MiniDB.cpp", "examples_2_mini_d_b_8cpp.html", "examples_2_mini_d_b_8cpp" ],
    [ "server/src/MiniDB.cpp", "server_2src_2_mini_d_b_8cpp.html", null ],
    [ "testing/minidb/MiniDB.cpp", "testing_2minidb_2_mini_d_b_8cpp.html", null ],
    [ "server/src/MiniDB.h", "server_2src_2_mini_d_b_8h.html", null ],
    [ "testing/minidb/MiniDB.h", "testing_2minidb_2_mini_d_b_8h.html", null ],
    [ "examples/Processing.cpp", "examples_2_processing_8cpp.html", "examples_2_processing_8cpp" ],
    [ "server/src/Processing.cpp", "server_2src_2_processing_8cpp.html", null ],
    [ "Processing.h", "_processing_8h.html", null ],
    [ "examples/rand_sse.cpp", "examples_2rand__sse_8cpp.html", "examples_2rand__sse_8cpp" ],
    [ "server/src/rand_sse.cpp", "server_2src_2rand__sse_8cpp.html", "server_2src_2rand__sse_8cpp" ],
    [ "rand_sse.h", "rand__sse_8h.html", "rand__sse_8h" ],
    [ "examples/Regex.cpp", "examples_2_regex_8cpp.html", "examples_2_regex_8cpp" ],
    [ "server/src/Regex.cpp", "server_2src_2_regex_8cpp.html", "server_2src_2_regex_8cpp" ],
    [ "testing/regex/Regex.cpp", "testing_2regex_2_regex_8cpp.html", "testing_2regex_2_regex_8cpp" ],
    [ "Regex.h", "_regex_8h.html", "_regex_8h" ],
    [ "examples/Server.cpp", "examples_2_server_8cpp.html", "examples_2_server_8cpp" ],
    [ "server/src/Server.cpp", "server_2src_2_server_8cpp.html", null ],
    [ "testing/server/Server.cpp", "testing_2server_2_server_8cpp.html", null ],
    [ "server/src/Server.h", "server_2src_2_server_8h.html", null ],
    [ "testing/server/Server.h", "testing_2server_2_server_8h.html", null ],
    [ "test.cpp", "test_8cpp.html", "test_8cpp" ]
];