var searchData=
[
  ['answer',['ANSWER',['../namespace_b_r_1_1_r_e_g_e_x_1_1_a_n_s_w_e_r.html',1,'BR::REGEX']]],
  ['br',['BR',['../namespace_b_r.html',1,'']]],
  ['check',['CHECK',['../namespace_b_r_1_1_c_h_e_c_k.html',1,'BR']]],
  ['client',['CLIENT',['../namespace_b_r_1_1_v_e_r_s_i_o_n_1_1_c_l_i_e_n_t.html',1,'BR::VERSION']]],
  ['code',['CODE',['../namespace_b_r_1_1_c_o_d_e.html',1,'BR']]],
  ['color',['COLOR',['../namespace_b_r_1_1_c_o_d_e_1_1_m_e_n_u_1_1_c_o_l_o_r.html',1,'BR::CODE::MENU']]],
  ['commands',['COMMANDS',['../namespace_b_r_1_1_c_o_n_s_o_l_e_1_1_c_o_m_m_a_n_d_s.html',1,'BR::CONSOLE']]],
  ['connect',['CONNECT',['../namespace_b_r_1_1_c_o_n_n_e_c_t.html',1,'BR']]],
  ['connection',['CONNECTION',['../namespace_b_r_1_1_c_o_d_e_1_1_c_o_n_n_e_c_t_i_o_n.html',1,'BR::CODE']]],
  ['console',['CONSOLE',['../namespace_b_r_1_1_c_o_d_e_1_1_c_o_n_s_o_l_e.html',1,'BR::CODE::CONSOLE'],['../namespace_b_r_1_1_c_o_n_s_o_l_e.html',1,'BR::CONSOLE']]],
  ['local',['LOCAL',['../namespace_b_r_1_1_s_q_l_i_t_e3_1_1_l_o_c_a_l.html',1,'BR::SQLITE3']]],
  ['main',['MAIN',['../namespace_b_r_1_1_c_o_d_e_1_1_m_e_n_u_1_1_m_a_i_n.html',1,'BR::CODE::MENU']]],
  ['memory',['MEMORY',['../namespace_b_r_1_1_s_q_l_i_t_e3_1_1_m_e_m_o_r_y.html',1,'BR::SQLITE3']]],
  ['menu',['MENU',['../namespace_b_r_1_1_c_o_d_e_1_1_m_e_n_u.html',1,'BR::CODE']]],
  ['message',['MESSAGE',['../namespace_b_r_1_1_c_o_n_s_o_l_e_1_1_m_e_s_s_a_g_e.html',1,'BR::CONSOLE']]],
  ['regex',['REGEX',['../namespace_b_r_1_1_r_e_g_e_x.html',1,'BR']]],
  ['server',['SERVER',['../namespace_b_r_1_1_v_e_r_s_i_o_n_1_1_s_e_r_v_e_r.html',1,'BR::VERSION']]],
  ['sqlite3',['SQLITE3',['../namespace_b_r_1_1_s_q_l_i_t_e3.html',1,'BR']]],
  ['version',['VERSION',['../namespace_b_r_1_1_v_e_r_s_i_o_n.html',1,'BR']]]
];
